name: Publish to Artifactory

on:
  # When Release Pull Request is merged
  pull_request:
    branches:
      - master
    types: [closed]

permissions:
  contents: write # for checkout and tag
  pull-requests: write # for comments
  packages: write # for publish

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install project dependencies
        run: pnpm install

      - name: Publish packages to Artifactory
        run: |
          # Replace the Artifactory URL and repository details with your own.
          ARTIFACTORY_URL="https://prafull.jfrog.io/artifactory/api/npm"
          ARTIFACTORY_REPO="npm"
          ARTIFACTORY_USERNAME="${{ secrets.ARTIFACTORY_USERNAME }}"
          ARTIFACTORY_PASSWORD="${{ secrets.ARTIFACTORY_PASSWORD }}"

          pnpm lerna publish from-package --registry "$ARTIFACTORY_URL/$ARTIFACTORY_REPO" --access public --dist-tag latest --registry "$ARTIFACTORY_URL/$ARTIFACTORY_REPO" --username "$ARTIFACTORY_USERNAME" --password "$ARTIFACTORY_PASSWORD"
        env:
          CI: true
