name: Publish to Artifactory

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install project dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm build

      - name: Publish packages to Artifactory
        run: |
          # 5= Replace the Artifactory URL and repository details with your own.
          ARTIFACTORY_URL="https://prafull.jfrog.io/artifactory/api/npm"
          ARTIFACTORY_REPO="npm"
          ARTIFACTORY_USERNAME="${{ secrets.ARTIFACTORY_USERNAME }}"
          ARTIFACTORY_PASSWORD="${{ secrets.ARTIFACTORY_PASSWORD }}"
          
          pnpm lerna publish from-package --registry "$ARTIFACTORY_URL/$ARTIFACTORY_REPO" --access public --dist-tag latest --registry "$ARTIFACTORY_URL/$ARTIFACTORY_REPO" --username "$ARTIFACTORY_USERNAME" --password "$ARTIFACTORY_PASSWORD"
        env:
          CI: true
